<?php

require_once  __DIR__ . '/bootstrap.php';

$configs = array(
    "services"=>array(
        "database" => ["type" => getenv('DATABASE_TYPE'), "uri" => getenv('DATABASE_URI')],
        "storage" => ["type" => getenv('STORAGE_TYPE'), "uri" =>  getenv("STORAGE_URI")],
        "index" => ["type" => getenv('INDEX_TYPE'), "uri" => getenv('INDEX_URI')]
    )
);

$configs["default_objects"] = [
    "graph" => \PhoNetworksAutogenerated\Network::class,
    "founder" => \PhoNetworksAutogenerated\User::class,
    "actor" => \PhoNetworksAutogenerated\User::class,
];

$group_id = getenv("GROUP_ID");
if($group_id<1) {
    echo "Error with group id.\n";
    exit;
}

$kernel = new \Pho\Kernel\Kernel($configs);

$founder = new \PhoNetworksAutogenerated\User(
    $kernel, $kernel->space(),
    getenv('FOUNDER_NICKNAME'),
    getenv('FOUNDER_EMAIL'),
    getenv('FOUNDER_PASSWORD')
);
$kernel->boot($founder);

$logger = getLogger();

$migration = new Migration(__DIR__ . '/google-plus-exports', $kernel, $logger);
$migration->migrate();
